//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLS_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participantes
    {
        public int idParticipante { get; set; }
        public int idProyecto { get; set; }
        public int idUsuario { get; set; }
        public int administrador { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
